"""Compatibility entry point for the redesigned Part Two report."""
import runpy
from pathlib import Path
runpy.run_path(str(Path(__file__).with_name('build_part_two_redesign.py')))
raise SystemExit
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
SITE=ROOT/'part-two'
data=json.loads((SITE/'results/results.json').read_text(encoding='utf-8'))
features=json.loads((SITE/'results/features.json').read_text(encoding='utf-8'))

def feature_controls(prefix):
    options=[(1,'Gradient alignment'),(2,'Auto crop'),(4,'White balance'),(8,'Auto contrast'),(16,'Colour mapping (experimental)')]
    labels=''.join(f'<label for="{prefix}-feature-{bit}"><input id="{prefix}-feature-{bit}" type="checkbox" data-feature="{bit}"><span>{label}</span></label>' for bit,label in options)
    return f'<fieldset class="feature-controls"><legend>Optional features · 可选效果</legend><div class="feature-options">{labels}</div><button type="button" class="reset-features">Reset to original · 恢复原版</button><p class="feature-status" aria-live="polite">Original pyramid NCC · No extra effects</p><details class="feature-details"><summary>Processing details</summary><p class="feature-metadata"></p><a class="crop-diagnostic" target="_blank" rel="noopener">View detected crop rectangle ↗</a><br><a class="baseline-download" target="_blank" rel="noopener">Original full-resolution NCC ↗</a></details></fieldset>'
rows=data['images'];lookup={r['id']:r for r in rows}
fmt=lambda v:f'({v[0]:+d}, {v[1]:+d})'
options=''.join(f'<option value="{r["id"]}" {"selected" if r["id"]=="00458u" else ""}>{r["source"]}</option>' for r in rows)
cards=[]
for r in rows:
    ident=r['id'];p=r['pyramid'];w,h=r['channel_size']
    cards.append(f'''<article class="result-card" data-id="{ident}"><button class="inspect-image" data-inspect="{ident}" aria-label="Inspect {r['source']}"><img src="results/{ident}/aligned.jpg" alt="NCC pyramid reconstruction of {r['source']}" width="600" height="510"><span>COMPARE ↗</span></button><div class="card-caption"><h3>{r['source']}</h3><span>{'HIGH RES' if w>1000 else 'LOW RES'}</span></div><p class="card-dimensions">{w} × {h} px per channel</p><p class="card-offsets">G {fmt(p['green'])} &nbsp; R {fmt(p['red'])}</p><p class="card-timing">{p['seconds']:.3f} s · Full-resolution pyramid</p><a href="results/{ident}/aligned-full.jpg" target="_blank" rel="noopener">Open full-resolution result ↗</a></article>''')
    cards[-1]=cards[-1].replace('<p class="card-dimensions">', feature_controls('card-'+ident)+'<p class="card-dimensions">')
experiments=[]
for ident,title in [('00458u','Fine edges on the locomotive'),('01657u','A portrait at full resolution'),('01728v','When ±15 pixels is not enough')]:
    r=lookup[ident]
    extra='The red vertical shift reaches the single-scale search boundary (+15 px); the pyramid finds +18 px at the original resolution.' if ident=='01728v' else 'The single-scale result is computed on a reduced image; the pyramid refines the offsets on the original pixels. Offsets below use each method’s own resolution.'
    experiments.append(f'''<article class="experiment"><h3>{title}</h3><p class="experiment-id">{r['source']}</p><div class="experiment-pair"><figure><img src="results/{ident}/single.jpg" alt="Single-scale NCC result for {ident}"><figcaption>SINGLE SCALE · {r['single_size'][0]} × {r['single_size'][1]}<br>G {fmt(r['single']['green'])} / R {fmt(r['single']['red'])}</figcaption></figure><figure><img src="results/{ident}/aligned.jpg" alt="Pyramid NCC result for {ident}"><figcaption>PYRAMID · {r['channel_size'][0]} × {r['channel_size'][1]}<br>G {fmt(r['pyramid']['green'])} / R {fmt(r['pyramid']['red'])}</figcaption></figure></div><p>{extra}</p></article>''')
trace_rows=''.join(f'<tr><td>1/{g["scale"]}</td><td>{g["width"]} × {g["height"]}</td><td>±{g["radius"]}</td><td>{fmt(g["offset"])}</td><td>{fmt(r["offset"])}</td></tr>' for g,r in zip(lookup['00458u']['pyramid']['green_trace'],lookup['00458u']['pyramid']['red_trace']))
max_time=max(r['pyramid']['seconds'] for r in rows)
html='''<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Reconstructing 18 Prokudin-Gorskii plates with NCC and a manually implemented image pyramid."><title>Images of the Russian Empire | Ke Yang · SYDE 671</title><link rel="stylesheet" href="../style.css"><link rel="stylesheet" href="part-two.css"><script src="part-two.js" defer></script></head><body>
<a class="skip" href="#main">Skip to content</a>
<header><div class="shell masthead"><a class="wordmark" href="../index.html">PHOTO<span>OF THE WORLD</span></a><div class="course">UNIVERSITY OF WATERLOO<span>SYDE 671 · Computational vision</span></div></div></header>
<nav aria-label="Part Two sections"><div class="shell nav-inner"><a class="assignment" href="../index.html">← PART ONE <span>/ PART TWO</span></a><div class="nav-links"><a href="#explore">01 Explore</a><a href="#method">02 Method</a><a href="#results">03 Results</a></div></div></nav>
<main id="main"><section class="hero shell" id="top"><div class="eyebrow"><i></i> ASSIGNMENT 01 / PART TWO / FIRST IMPLEMENTATION</div><h1>Images of the<br><em>Russian Empire.</em></h1><div class="hero-bottom"><p>Three monochrome exposures. One colour photograph.<br>Reconstructing the Prokudin-Gorskii collection, one pixel shift at a time.</p><div class="byline">IMPLEMENTATION & EXPERIMENTS<strong>Ke Yang</strong><span>Python · NumPy · Pillow</span></div></div><div class="metric-strip"><div><strong>18</strong><span>PROVIDED PLATES</span></div><div><strong>6</strong><span>HIGH-RESOLUTION SCANS</span></div><div><strong>NCC</strong><span>ONE METRIC, FIXED PARAMETERS</span></div><div><strong>__MAX_TIME__ s</strong><span>SLOWEST PYRAMID ALIGNMENT</span></div></div></section>
<section class="shell study" id="explore"><div class="section-heading"><span class="number">01</span><div><div class="eyebrow">SEE THE DIFFERENCE</div><h2>Bring the channels together.</h2></div></div><p class="intro">Each plate records blue, green, and red exposures separately. Simply stacking them creates coloured outlines. Translating the channels brings the scene back into alignment.</p>
<div class="explorer"><div class="explorer-toolbar"><div><label for="plate-select">CHOOSE A PLATE</label><select id="plate-select">__OPTIONS__</select></div><a id="full-result" href="results/00458u/aligned-full.jpg" target="_blank" rel="noopener">Open full-resolution result ↗</a></div>
<div class="comparison" id="comparison"><img id="after-image" src="results/00458u/aligned.jpg" alt="Pyramid-aligned locomotive photograph"><img id="before-image" class="before-layer" src="results/00458u/before.jpg" alt="Unaligned locomotive photograph on the same canvas"><span class="compare-label before-label">BEFORE</span><span class="compare-label after-label">PYRAMID NCC</span><div class="divider" aria-hidden="true"><span>↔</span></div></div>
<div class="comparison-controls"><label for="comparison-slider">Drag to compare the same image area</label><input id="comparison-slider" type="range" min="0" max="100" value="50" aria-valuetext="50% before, 50% aligned"><div><span>ALIGNED</span><output id="comparison-value">50 / 50</output><span>UNALIGNED</span></div></div><div class="result-readout" aria-live="polite"><span id="selected-size"></span><span id="selected-green"></span><span id="selected-red"></span><span id="selected-time"></span></div></div>
<p class="caption">Both sides use the same crop in the blue channel’s coordinates. Only areas without valid data in all three shifted channels are removed. Remaining coloured scan borders are intentionally visible in this baseline.</p>
</section>
<section class="method-band" id="method"><div class="shell study"><div class="section-heading"><span class="number">02</span><div><div class="eyebrow">FROM A GLASS PLATE TO RGB</div><h2>Split. Search. Refine.</h2></div></div><p class="intro">A translation-only model, implemented from scratch. The blue channel is the fixed reference; green and red are aligned independently.</p>
<div class="process-grid"><div class="source-plate"><img src="results/00458u/plate.jpg" alt="Original three-exposure locomotive plate, blue on top, green in the middle, red at the bottom" loading="lazy"><span>ORIGINAL PLATE · B / G / R</span></div><div class="process-details"><h3>01 / Three equal sections</h3><p>Use h = floor(H / 3), then take three h-row sections. Any final one or two leftover rows are discarded. This is a coarse separation: scan borders and scene positions need not line up.</p><div class="channels">__CHANNELS__</div><p class="caption">Dashed boxes indicate the central 80% used as the starting scoring region: 10% is excluded from each edge. Candidate shifts must also overlap valid interiors in both channels.</p><h3>02 / Search for the best match</h3><p>On images no larger than 400 pixels on the longest side, test every integer shift from −15 to +15 in each direction. Choose the largest zero-mean normalized cross-correlation (NCC).</p><div class="equation">NCC(A, B) = Σ[(A − Ā)(B − B̄)] / √[Σ(A − Ā)² · Σ(B − B̄)²]</div><p>Subtracting each region’s mean reduces sensitivity to brightness offsets; normalization reduces sensitivity to contrast scaling. Only overlapping interior pixels enter the score. There is no wraparound.</p></div></div>
<div class="pyramid-method"><div><h3>03 / Coarse to fine</h3><p>For the original-resolution run, build the pyramid manually: Gaussian smoothing (σ = 1) followed by factor-two subsampling. Stop when the longest side is at most 192 pixels.</p><p>Search ±15 pixels on the smallest level, double the estimated shift at the next level, then search only ±2 pixels around that prediction. Continue to the original resolution.</p><p>Finally, translate the original channels and stack them as RGB. Crop to their common valid overlap. This crop removes missing-data edges; it does not automatically detect scan borders.</p></div><div class="trace"><div class="eyebrow">ACTUAL SEARCH TRACE / 00458u.jpg</div><div class="table-scroll"><table><thead><tr><th>Scale</th><th>Channel size</th><th>Search</th><th>G (dx, dy)</th><th>R (dx, dy)</th></tr></thead><tbody>__TRACE__</tbody></table></div><p class="caption">Offsets are measured in pixels of that level. Positive dx moves right; positive dy moves down.</p></div></div>
</div></section>
<section class="shell study" id="experiments"><div class="section-heading"><span class="number">03</span><div><div class="eyebrow">THREE EXPERIMENTS</div><h2>Small search. Bigger picture.</h2></div></div><p class="intro">The single-scale baseline and pyramid method share the same NCC score and border exclusion. These examples show a detailed object, a portrait, and a shift outside the baseline search window.</p><div class="experiment-grid">__EXPERIMENTS__</div><p class="caption">For large scans, single-scale alignment runs on a reduced image, while pyramid alignment reaches the original resolution. Their timings are not a same-resolution speed benchmark.</p></section>
<section class="gallery-band" id="results"><div class="shell study"><div class="section-heading"><span class="number">04</span><div><div class="eyebrow">THE COMPLETE DATASET</div><h2>Eighteen plates, reconstructed.</h2></div></div><p class="intro">Every provided image, processed with the same settings. Switch the gallery view or select a photo to inspect it in the comparison viewer.</p><div class="gallery-toolbar"><div class="mode-buttons" role="group" aria-label="Gallery result type"><button data-mode="pyramid" aria-pressed="true">Pyramid NCC</button><button data-mode="single" aria-pressed="false">Single-scale NCC</button><button data-mode="before" aria-pressed="false">Before alignment</button></div><a href="results/offsets.csv" download>Download offsets CSV ↓</a></div><p id="gallery-description" class="caption" aria-live="polite">Pyramid NCC · Offsets measured at each original channel’s resolution.</p><div class="results-grid">__CARDS__</div></div></section>
<section class="shell study discussion" id="discussion"><div class="section-heading"><span class="number">05</span><div><div class="eyebrow">WHAT THIS FIRST VERSION SHOWS</div><h2>Alignment is only the beginning.</h2></div></div><div class="discussion-grid"><article><h3>Scene detail lines up.</h3><p>The locomotive’s edges and the architectural details lose much of their coloured ghosting after alignment. For 01728v, the single-scale red shift hits +15 pixels, while the pyramid reaches +18 pixels and reduces the remaining displacement.</p></article><article><h3>Some differences remain.</h3><p>00056v has conspicuous blotches in the reconstructed image. Scan damage, channel-specific colour response, and motion between exposures cannot all be corrected by a single translation. Small fringes can remain even when the dominant structures align.</p></article><article><h3>Borders are a separate problem.</h3><p>Ignoring borders during scoring prevents them from dominating the match. It does not remove them from the final image. This baseline retains scan borders; automatic border detection, white balance, and colour correction have not been applied.</p></article></div><div class="implementation-note"><strong>First-version scope</strong><p>All 18 provided plates are included, with low-resolution single-scale results, original-resolution pyramid results, offsets, timings, and intermediate channels. Additional self-selected collection images and optional enhancements are still future work.</p></div><div class="download-links"><a href="results/results.json" download>Full metrics & pyramid traces ↓</a><a href="../scripts/alignment.py" download>Alignment code ↓</a><a href="../scripts/run_alignment.py" download>Batch runner ↓</a></div></section>
<aside class="takeaway"><div class="shell"><span class="eyebrow">THE TAKEAWAY</span><p>Three exposures.<br>A world in colour.</p><span>Find the correspondence. Recover the photograph.</span></div></aside></main>
<footer class="shell footer"><div><strong>Ke Yang</strong><span>SYDE 671 · Assignment 1 · Part Two</span></div><div class="footer-actions"><a href="../index.html">← Part One</a><a href="#top">Back to top ↑</a></div><p>Photographs: Sergei Mikhailovich Prokudin-Gorskii · Provided assignment dataset. Reconstruction: zero-mean NCC with integer translations. Timings measure the two channel-alignment searches, excluding file I/O and output generation.</p></footer>
<script id="alignment-data" type="application/json">__DATA__</script></body></html>'''
channels=''.join(f'<figure><div class="channel-image"><img src="results/00458u/channel-{c}.jpg" alt="{name} exposure of the locomotive" loading="lazy"><i></i></div><figcaption>{name.upper()} / {pos}</figcaption></figure>' for c,name,pos in [('b','Blue','TOP'),('g','Green','MIDDLE'),('r','Red','BOTTOM')])
for key,value in {'__OPTIONS__':options,'__MAX_TIME__':f'{max_time:.2f}','__CHANNELS__':channels,'__TRACE__':trace_rows,'__EXPERIMENTS__':''.join(experiments),'__CARDS__':''.join(cards),'__DATA__':json.dumps(data)}.items():html=html.replace(key,value)
html=html.replace('FIRST IMPLEMENTATION','BASELINE + OPTIONAL FEATURES')
html=html.replace('<div class="result-readout"', '<div id="viewer-features">'+feature_controls('viewer')+'</div><div class="result-readout"')
html=html.replace('Both sides use the same crop in the blue channel’s coordinates. Only areas without valid data in all three shifted channels are removed. Remaining coloured scan borders are intentionally visible in this baseline.', 'With all options off, compare unaligned RGB against the original pyramid NCC result. With an effect enabled, compare the original NCC result against your selected effects on exactly the same image area. Auto crop applies the detected rectangle to both sides for a fair comparison. Each photo remembers its own options while this page is open.')
html=html.replace('Every provided image, processed with the same settings. Switch the gallery view or select a photo to inspect it in the comparison viewer.', 'Every provided image, processed with the same settings. Use the checkboxes beneath each photo to combine optional effects. All options start off. Select a photo to inspect the original and edited versions above.')
html=html.replace('This baseline retains scan borders; automatic border detection, white balance, and colour correction have not been applied.', 'The original baseline retains scan borders. Optional crop detection and colour adjustments are now available below each photograph; they can be switched off independently.')
html=html.replace('Additional self-selected collection images and optional enhancements are still future work.', 'Five optional features now have reversible per-photo controls. Additional self-selected collection images are still future work.')
feature_section='''<section class="shell study feature-methods" id="features"><div class="section-heading"><span class="number">+</span><div><div class="eyebrow">BELLS & WHISTLES</div><h2>Choose what each photograph needs.</h2></div></div><p class="intro">Five independent options, 32 combinations per photograph. The original intensity-NCC images and measurements are preserved. White balance and colour mapping are hypotheses about appearance, not verified historical colours.</p><div class="discussion-grid"><article><h3>Gradient alignment</h3><p>Re-run the full-resolution pyramid with NCC on smoothed gradient magnitudes at each level, then apply the new shifts to the original channels. This emphasizes structure rather than raw brightness. The offsets shown below each image update when this option is selected.</p></article><article><h3>Automatic crop</h3><p>Detect row and column transitions near the image edges, supported by extreme brightness or inconsistent colour. A 15% search limit prevents deep cuts; it is not a fixed crop amount. If no convincing edge is found, that side stays unchanged. The detection overlay shows the measured rectangle.</p></article><article><h3>Gray-world white balance</h3><p>Estimate RGB means from the detected interior, excluding near-black and near-white samples; scale channels toward a shared mean. Gains are limited and a common exposure factor protects highlights. Scenes dominated by one colour can be overcorrected; leave this option off when it looks worse.</p></article><article><h3>Automatic contrast</h3><p>Stretch the detected interior’s 1st–99th percentile intensity range to [0, 1], using the same mapping for all RGB channels. This follows white balance when both are selected. Values outside the chosen range are clipped, so extreme details may be lost.</p></article><article><h3>Experimental colour mapping</h3><p>A fixed 3 × 3 matrix mixes each channel with 15% luminance, retaining 85% of chroma. Neutral colours stay neutral and saturation is gently reduced. Applied in encoded RGB, this is an aesthetic experiment, not a calibrated correction of the original filters.</p></article><article><h3>Reversible combinations</h3><p>Processing order: alignment → detected crop → white balance → contrast → colour matrix. Tone statistics exclude detected borders even when crop is off. Alignment is computed at original resolution; optional tone variants are web previews up to 1100 px. The original full-resolution downloads remain available.</p></article></div><div class="download-links"><a href="results/features.json" download>Feature parameters & crop bounds ↓</a><a href="../scripts/enhancements.py" download>Enhancement algorithms ↓</a></div></section>'''
html=html.replace('<section class="shell study discussion"',feature_section+'<section class="shell study discussion"')
html=html.replace('</body>', '<script id="feature-data" type="application/json">'+json.dumps(features)+'</script></body>')
(SITE/'index.html').write_text(html,encoding='utf-8')
print('Built Part Two report for',len(rows),'images.')
