"""Build the English-only two-section Part Two presentation page."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / 'part-two'
RESULTS = SITE / 'results'
baseline = json.loads((RESULTS / 'results.json').read_text(encoding='utf-8'))
features = json.loads((RESULTS / 'features.json').read_text(encoding='utf-8'))
rows = baseline['images']
feature_map = {r['id']: r for r in features['images']}
plate_count = len(rows)
high_res_count = sum(1 for r in rows if r['channel_size'][0] > 1000)

def fmt(pair):
    return f'({pair[0]:+d}, {pair[1]:+d})'

def feature_controls(prefix):
    labels = [(1, 'Gradient alignment'), (2, 'Automatic crop'), (4, 'White balance'),
              (8, 'Automatic contrast'), (16, 'Colour mapping (experimental)')]
    inputs = ''.join(
        f'<label for="{prefix}-feature-{bit}"><input id="{prefix}-feature-{bit}" type="checkbox" data-feature="{bit}"><span>{label}</span></label>'
        for bit, label in labels
    )
    return f'''<fieldset class="feature-controls"><legend>Optional features</legend><div class="feature-options">{inputs}</div><button type="button" class="reset-features">Reset to original</button><p class="feature-status" aria-live="polite">Original pyramid NCC · No extra effects</p><details class="feature-details"><summary>Processing details</summary><p class="feature-metadata"></p><a class="crop-diagnostic" target="_blank" rel="noopener">View detected crop rectangle ↗</a><br><a class="baseline-download" target="_blank" rel="noopener">Original full-resolution NCC ↗</a></details></fieldset>'''

options = ''.join(f'<option value="{r["id"]}" {"selected" if r["id"] == "00458u" else ""}>{r["source"]}</option>' for r in rows)
cards = []
table_rows = []
for r in rows:
    ident = r['id']; p = r['pyramid']; w, h = r['channel_size']
    cards.append(f'''<article class="result-card" data-id="{ident}"><button class="inspect-image" data-inspect="{ident}" aria-label="Inspect {r['source']}"><img src="results/{ident}/aligned.jpg" alt="Pyramid NCC reconstruction of {r['source']}" width="600" height="510"><span>COMPARE ↗</span></button><div class="card-caption"><h3>{r['source']}</h3><span>{'HIGH RESOLUTION' if w > 1000 else 'LOW RESOLUTION'}</span></div>{feature_controls('card-' + ident)}<p class="card-dimensions">{w} × {h} px per channel</p><p class="card-offsets">G {fmt(p['green'])} &nbsp; R {fmt(p['red'])}</p><p class="card-timing">{p['seconds']:.3f} s · Full-resolution pyramid</p><a href="results/{ident}/aligned-full.jpg" target="_blank" rel="noopener">Open full-resolution result ↗</a></article>''')
    sw, sh = r['single_size']
    table_rows.append(f'''<tr><td>{r['source']}</td><td>{w} × {h}</td><td>{sw} × {sh}</td><td>{r['single']['seconds']:.3f}</td><td>{r['pyramid']['seconds']:.3f}</td><td>{fmt(r['single']['green'])}</td><td>{fmt(r['single']['red'])}</td><td>{fmt(p['green'])}</td><td>{fmt(p['red'])}</td></tr>''')

trace_rows = ''.join(f'<tr><td>1/{g["scale"]}</td><td>{g["width"]} × {g["height"]}</td><td>±{g["radius"]}</td><td>{fmt(g["offset"])}</td><td>{fmt(r["offset"])}</td></tr>' for g, r in zip(next(x for x in rows if x['id'] == '00458u')['pyramid']['green_trace'], next(x for x in rows if x['id'] == '00458u')['pyramid']['red_trace']))
max_time = max(r['pyramid']['seconds'] for r in rows)
channels = ''.join(f'<figure><img src="results/00458u/channel-{c}.jpg" alt="{name} exposure of the locomotive"><figcaption>{name.upper()} · {position}</figcaption></figure>' for c, name, position in [('b', 'Blue', 'top'), ('g', 'Green', 'middle'), ('r', 'Red', 'bottom')])
table = ''.join(table_rows)

html = '''<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Ke Yang's SYDE 671 reconstruction of the Prokudin-Gorskii Russian Empire photographs."><title>Images of the Russian Empire | Ke Yang · SYDE 671</title><link rel="stylesheet" href="../style.css"><link rel="stylesheet" href="part-two.css"><script src="part-two.js" defer></script></head><body>
<a class="skip" href="#main">Skip to content</a>
<header><div class="shell masthead"><a class="wordmark" href="../index.html">PHOTO<span>OF THE WORLD</span></a><div class="course">UNIVERSITY OF WATERLOO<span>SYDE 671 · Computational vision</span></div></div></header>
<nav aria-label="Part Two sections"><div class="shell nav-inner"><a class="assignment" href="../index.html">← PART ONE <span>/ PART TWO</span></a><div class="nav-links"><a href="#explore">01 Explore</a><a href="#results">04 Results</a></div></div></nav>
<main id="main">
<section class="hero shell" id="top"><div class="eyebrow"><i></i> ASSIGNMENT 01 / PART TWO</div><h1>Images of the<br><em>Russian Empire.</em></h1><div class="hero-bottom"><p>Three monochrome exposures. One colour photograph.<br>Reconstructing the Prokudin-Gorskii collection, one pixel shift at a time.</p><div class="byline">IMPLEMENTATION & EXPERIMENTS<strong>Ke Yang</strong><span>Python · NumPy · Pillow</span></div></div><div class="metric-strip"><div><strong>__PLATE_COUNT__</strong><span>PROVIDED PLATES</span></div><div><strong>__HIGH_RES_COUNT__</strong><span>HIGH-RESOLUTION SCANS</span></div><div><strong>NCC</strong><span>FIXED BASELINE METRIC</span></div><div><strong>__MAX_TIME__ s</strong><span>SLOWEST PYRAMID RUN</span></div></div></section>
<section class="shell study" id="explore"><div class="section-heading"><span class="number">01</span><div><div class="eyebrow">METHOD, INTERACTION, AND OPTIONAL FEATURES</div><h2>Split. Search. Refine.</h2></div></div>
<div class="method-copy"><p><strong>1 / Channel extraction.</strong> Each vertical plate contains three grayscale exposures: blue at the top, green in the middle, and red at the bottom. The core split uses <code>height = gray.shape[0] // 3</code> and takes the three consecutive sections. Grayscale is appropriate because each exposure is a single-channel luminance record captured through a separate colour filter.</p>
<p><strong>2 / Baseline NCC alignment.</strong> Blue is the reference channel. Green and red are translated independently until their match score is largest. For a recorded shift such as <code>G = (+1, +1)</code>, green moves one pixel right and one pixel down.</p><div class="equation">NCC(A, B) = Σ[(A − Ā)(B − B̄)] / √[Σ(A − Ā)² · Σ(B − B̄)²]</div><p>Before scoring, the current baseline ignores 10% of each edge and uses only valid overlap. The 10% edge exclusion is a scoring safeguard; automatic cropping is a separate optional feature below.</p>
<p><strong>3 / Single-scale alignment.</strong> This implementation uses a reduced single-scale baseline for large scans: channels are capped at a longest side of 400 pixels, while smaller plates stay at their native size. It then tests every integer shift in a ±15-pixel window and keeps the highest NCC score. The 400-pixel cap is an engineering choice for a quick comparison, not a requirement of the assignment; a full-resolution single-scale search would be slower and would need a wider window for large displacements.</p>
<p><strong>4 / Coarse-to-fine pyramid.</strong> Large channels are repeatedly smoothed and downsampled by two until the longest side is at most 192 pixels. The smallest level searches ±15 pixels. At each finer level, the previous offset is doubled and refined in a ±2-pixel window. The loop is equivalent to <code>while max(refs[-1].shape) &gt; coarse_size: refs.append(downsample(refs[-1]))</code>.</p>
<p><strong>5 / Common valid canvas.</strong> After translation, only the rectangle shared by B, G, and R is retained. Its bounds use <code>x0 = max(dx)</code>, <code>x1 = min(width + dx)</code>, <code>y0 = max(dy)</code>, and <code>y1 = min(height + dy)</code> across the three offsets. This removes missing pixels caused by displacement.</p></div>
<div class="explorer"><div class="explorer-toolbar"><div><label for="plate-select">CHOOSE A PLATE</label><select id="plate-select">__OPTIONS__</select></div><a id="full-result" href="results/00458u/aligned-full.jpg" target="_blank" rel="noopener">Open original full-resolution result ↗</a></div><div class="comparison" id="comparison"><img id="after-image" src="results/00458u/aligned.jpg" alt="Pyramid-aligned locomotive photograph"><img id="before-image" class="before-layer" src="results/00458u/before.jpg" alt="Unaligned locomotive photograph on the same canvas"><span class="compare-label before-label">BEFORE</span><span class="compare-label after-label">PYRAMID NCC</span><div class="divider" aria-hidden="true"><span>↔</span></div></div><div class="comparison-controls"><label for="comparison-slider">Drag to compare the same image area</label><input id="comparison-slider" type="range" min="0" max="100" value="50" aria-valuetext="50% unaligned, 50% aligned"><div><span>ALIGNED</span><output id="comparison-value">50 / 50</output><span>UNALIGNED</span></div></div><div id="viewer-features">__VIEWER_FEATURES__</div><div class="result-readout" aria-live="polite"><span id="selected-size"></span><span id="selected-green"></span><span id="selected-red"></span><span id="selected-time"></span></div></div>
<p class="caption">The viewer compares the same image area. With optional features enabled, it compares the original NCC result against the selected effects. Every option is reversible.</p>
<div class="feature-methods"><div class="eyebrow">OPTIONAL FEATURES</div><h3>What the switches do</h3><div class="feature-explanation"><article><h4>Gradient alignment</h4><p>Instead of comparing raw intensity, compare image structure with <code>E(x,y) = √(I<sub>x</sub>² + I<sub>y</sub>²)</code>. The implementation uses <code>gy, gx = np.gradient(smooth)</code> and <code>magnitude = np.hypot(gx, gy)</code>.</p></article><article><h4>Automatic cropping</h4><p>The image is reduced to at most 900 pixels, all four edges are inspected, and the detector looks for brightness transitions, near-black or near-white borders, and unusual channel differences. It searches for the transition from border to real picture instead of removing a fixed margin. A similar border colour or a large white sky can still confuse the detector.</p></article><article><h4>Automatic contrast</h4><p>Use the 1st and 99th percentiles of the interior: <code>lo, hi = np.percentile(region, (1, 99))</code>, then <code>result = clip((image − lo) / (hi − lo), 0, 1)</code>. The same mapping is applied to all three channels.</p></article><article><h4>Gray-world white balance</h4><p>Assume the average colour is close to gray. With channel means <code>means</code>, use <code>gains = means.mean() / means</code> and <code>balanced = image * gains</code>. A scene dominated by grass, sky, or a red wall may be overcorrected.</p></article><article><h4>Experimental colour mapping</h4><p>Use <code>M = 0.85I + 0.15L</code>, where every row of <code>L</code> is <code>[0.2126, 0.7152, 0.0722]</code>. This retains 85% of the original colour, adds 15% luminance, slightly reduces intense colours, and keeps neutral gray close to neutral. It is an experimental visual mapping, not calibrated historical colour recovery.</p></article><article><h4>Feature toggles</h4><p>Each photograph has independent switches. All are off by default, so the original pyramid NCC result is preserved. The page can combine the five effects and reset any image to the baseline.</p></article></div></div>
<div class="pyramid-example"><div><div class="eyebrow">PYRAMID EXAMPLE / 00458U.JPG</div><h3>One coarse search, then local refinement.</h3><p>The table records the actual search path for 00458u. Offsets are in pixels at each level. Positive x moves right; positive y moves down.</p></div><div class="table-scroll"><table><thead><tr><th>Scale</th><th>Channel size</th><th>Search</th><th>G offset</th><th>R offset</th></tr></thead><tbody>__TRACE__</tbody></table></div></div>
</section>
<section class="gallery-band" id="results"><div class="shell study"><div class="section-heading"><span class="number">04</span><div><div class="eyebrow">RESULTS AND MEASUREMENTS</div><h2>__PLATE_COUNT__ plates, reconstructed.</h2></div></div><p class="intro">The cards below show every input. Each row in the table records the reduced single-scale baseline and the original-resolution pyramid run.</p><div class="gallery-toolbar"><div class="mode-buttons" role="group" aria-label="Gallery result type"><button data-mode="pyramid" aria-pressed="true">Pyramid NCC</button><button data-mode="single" aria-pressed="false">Single-scale NCC</button><button data-mode="before" aria-pressed="false">Before alignment</button></div><a href="results/offsets.csv" download>Download offsets CSV ↓</a></div><p id="gallery-description" class="caption" aria-live="polite">Pyramid NCC · Original channel dimensions and full-resolution offsets.</p><div class="results-grid">__CARDS__</div><div class="data-table"><div class="eyebrow">COMPLETE MEASUREMENT TABLE</div><h3>Time, offsets, and channel dimensions</h3><div class="table-scroll"><table><thead><tr><th>Image</th><th>Channel size</th><th>Single input</th><th>Single time (s)</th><th>Pyramid time (s)</th><th>Single G (dx, dy)</th><th>Single R (dx, dy)</th><th>Pyramid G (dx, dy)</th><th>Pyramid R (dx, dy)</th></tr></thead><tbody>__TABLE__</tbody></table></div><p class="caption">Times include the two channel searches and exclude file loading and image export. “Channel size” is the original input used by the pyramid; “Single input” records the size used by the reduced baseline. The 400 px cap is an implementation choice for large scans, while small plates use native dimensions.</p></div></div></section>
</main><aside class="takeaway"><div class="shell"><span class="eyebrow">THE TAKEAWAY</span><p>Three exposures.<br>A world in colour.</p><span>Find the correspondence. Recover the photograph.</span></div></aside><footer class="shell footer"><div><strong>Ke Yang</strong><span>SYDE 671 · Assignment 1 · Part Two</span></div><div class="footer-actions"><a href="../index.html">← Part One</a><a href="#top">Back to top ↑</a></div><p>Prokudin-Gorskii reconstruction using zero-mean NCC, a manual image pyramid, and optional enhancement experiments.</p></footer><script id="alignment-data" type="application/json">__DATA__</script><script id="feature-data" type="application/json">__FEATURE_DATA__</script></body></html>'''

for key, value in {
    '__PLATE_COUNT__': str(plate_count), '__HIGH_RES_COUNT__': str(high_res_count), '__MAX_TIME__': f'{max_time:.2f}', '__OPTIONS__': options, '__TABLE__': table,
    '__TRACE__': trace_rows, '__CARDS__': ''.join(cards), '__DATA__': json.dumps(baseline),
    '__FEATURE_DATA__': json.dumps(features), '__VIEWER_FEATURES__': feature_controls('viewer')
}.items():
    html = html.replace(key, value)
(SITE / 'index.html').write_text(html, encoding='utf-8')
print(f'Built redesigned English-only Part Two page for {len(rows)} images.')
